DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   first VARCHAR(255) NOT NULL,
   last VARCHAR(255) NOT NULL,
   profilepicurl VARCHAR(500),
   bio VARCHAR(255),
   email VARCHAR(255) UNIQUE NOT NULL,
   pass VARCHAR(255) NOT NULL,   
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);