-- DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS friend_requests;

CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   first VARCHAR(255) NOT NULL,
   last VARCHAR(255) NOT NULL,
   profilepicurl VARCHAR(500),
   bio VARCHAR(255),
   email VARCHAR(255) UNIQUE NOT NULL,
   pass VARCHAR(255) NOT NULL,   
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE friends(
  id SERIAL PRIMARY KEY,
  user_1 INTEGER REFERENCES users(id),
  user_2 INTEGER REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE friend_requests(
  id SERIAL PRIMARY KEY,
  sender_id INTEGER REFERENCES users(id),
  receiver_id INTEGER REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);